version: "3"
services:
  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    env_file:
      - ./env/mysql.env
    ports:
      - "3306:3306"
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
    restart: always
