version: "3"
services:
  nginx-server:
    image: nginx:1.20-alpine
    container_name: nginx-server
    ports:
      - "80:80"
    # 自定义 DNS 服务器
    dns:
      - 223.5.5.5
      - 223.6.6.6
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
      - ./logs:/var/log/nginx
    restart: always
    # 检查容器是否健康运行
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
